TOP = ../..
include $(TOP)/configure/CONFIG

# Additional libraries
DB += $(ASYN)/db/asynRecord.db
DB += $(IOCSTATS)/db/ioc.db

# Install databases, templates, and substitutions
DB += rectangle.db

# Add custom rules after this line
include $(TOP)/configure/RULES
