TOP = ../..
include $(TOP)/configure/CONFIG

# Additional libraries
DB += $(ASYN)/db/asynRecord.db

# Install databases, templates, and substitutions
DB += quadratic.db

# Add custom rules after this line
include $(TOP)/configure/RULES
