TOP = ../..
include $(TOP)/configure/CONFIG

#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

# Create and install (or just install)
# databases, templates, substitutions like this
DB += $(ASYN)/db/asynRecord.db
DB += example.db

# Add custom rules after this line
include $(TOP)/configure/RULES
